/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessHeartDiseaseRouteImport } from './routes/assess.heart-disease'
import { Route as AssessDiabetesRouteImport } from './routes/assess.diabetes'
import { Route as AssessDiseaseRouteImport } from './routes/assess.$disease'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessHeartDiseaseRoute = AssessHeartDiseaseRouteImport.update({
  id: '/assess/heart-disease',
  path: '/assess/heart-disease',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessDiabetesRoute = AssessDiabetesRouteImport.update({
  id: '/assess/diabetes',
  path: '/assess/diabetes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessDiseaseRoute = AssessDiseaseRouteImport.update({
  id: '/assess/$disease',
  path: '/assess/$disease',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/assess/$disease': typeof AssessDiseaseRoute
  '/assess/diabetes': typeof AssessDiabetesRoute
  '/assess/heart-disease': typeof AssessHeartDiseaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/assess/$disease': typeof AssessDiseaseRoute
  '/assess/diabetes': typeof AssessDiabetesRoute
  '/assess/heart-disease': typeof AssessHeartDiseaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/assess/$disease': typeof AssessDiseaseRoute
  '/assess/diabetes': typeof AssessDiabetesRoute
  '/assess/heart-disease': typeof AssessHeartDiseaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/privacy'
    | '/results'
    | '/terms'
    | '/assess/$disease'
    | '/assess/diabetes'
    | '/assess/heart-disease'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/privacy'
    | '/results'
    | '/terms'
    | '/assess/$disease'
    | '/assess/diabetes'
    | '/assess/heart-disease'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/privacy'
    | '/results'
    | '/terms'
    | '/assess/$disease'
    | '/assess/diabetes'
    | '/assess/heart-disease'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  TermsRoute: typeof TermsRoute
  AssessDiseaseRoute: typeof AssessDiseaseRoute
  AssessDiabetesRoute: typeof AssessDiabetesRoute
  AssessHeartDiseaseRoute: typeof AssessHeartDiseaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/heart-disease': {
      id: '/assess/heart-disease'
      path: '/assess/heart-disease'
      fullPath: '/assess/heart-disease'
      preLoaderRoute: typeof AssessHeartDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/diabetes': {
      id: '/assess/diabetes'
      path: '/assess/diabetes'
      fullPath: '/assess/diabetes'
      preLoaderRoute: typeof AssessDiabetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/$disease': {
      id: '/assess/$disease'
      path: '/assess/$disease'
      fullPath: '/assess/$disease'
      preLoaderRoute: typeof AssessDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  TermsRoute: TermsRoute,
  AssessDiseaseRoute: AssessDiseaseRoute,
  AssessDiabetesRoute: AssessDiabetesRoute,
  AssessHeartDiseaseRoute: AssessHeartDiseaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
